# Future: PDF report export using reportlab or fpdf2
# Currently: generates a plain-text summary report

from datetime import datetime
import json


def generate_text_report(analysis_result: dict, candidate_name: str = "Candidate") -> str:
    """
    Generate a plain-text summary report of the analysis.

    Args:
        analysis_result: Full result dict from the analysis pipeline
        candidate_name: Name extracted from resume

    Returns:
        Formatted text report as string
    """
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    score = analysis_result.get("score", 0)
    label = analysis_result.get("score_label", "N/A")
    matched = analysis_result.get("matched_skills", [])
    missing = analysis_result.get("missing_skills", [])
    category = analysis_result.get("category", {})
    suggestions = analysis_result.get("suggestions", {})

    lines = [
        "=" * 60,
        "           RESUMEIQ ANALYSIS REPORT",
        "=" * 60,
        f"Date       : {now}",
        f"Candidate  : {candidate_name}",
        f"Match Score: {score}% — {label}",
        "",
        "-" * 60,
        "JOB CATEGORY PREDICTION",
        "-" * 60,
        f"Detected Category : {category.get('category', 'N/A')}",
        f"Confidence        : {category.get('confidence', 0)}%",
        "",
        "-" * 60,
        f"MATCHED SKILLS ({len(matched)} found)",
        "-" * 60,
    ]
    lines += [f"  ✅ {s}" for s in matched] or ["  None"]

    lines += [
        "",
        "-" * 60,
        f"MISSING SKILLS ({len(missing)} gaps)",
        "-" * 60,
    ]
    lines += [f"  ❌ {s}" for s in missing] or ["  None — great match!"]

    lines += [
        "",
        "-" * 60,
        "IMPROVEMENT SUGGESTIONS",
        "-" * 60,
    ]
    for tip in suggestions.get("general_tips", []):
        # Strip markdown formatting for plain text
        tip_clean = tip.replace("**", "").replace("*", "")
        lines.append(f"  • {tip_clean}")

    lines += [
        "",
        "=" * 60,
        "Generated by ResumeIQ — Free AI Resume Screening Tool",
        "=" * 60,
    ]

    return "\n".join(lines)


def generate_json_report(analysis_result: dict) -> str:
    """
    Export full analysis result as formatted JSON string.

    Args:
        analysis_result: Full result dict

    Returns:
        JSON-formatted string
    """
    return json.dumps(analysis_result, indent=2, default=str)


# ── Future PDF generation ──────────────────────────────────────────────────────
# Uncomment and install fpdf2 to enable:
# pip install fpdf2

# from fpdf import FPDF
#
# def generate_pdf_report(analysis_result: dict, output_path: str) -> str:
#     pdf = FPDF()
#     pdf.add_page()
#     pdf.set_font("Helvetica", size=12)
#     report_text = generate_text_report(analysis_result)
#     for line in report_text.split("\n"):
#         pdf.cell(0, 8, txt=line, ln=True)
#     pdf.output(output_path)
#     return output_path
